language: node_js
node_js:
- 10.15.1

script:
- yarn test

deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_TOKEN
  on:
    branch: master    

notifications:
  email:
  - $EMAIL_ADDRESS
