version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: 'sudo npm i pnpm -g'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: 'pnpm install --frozen-lockfile'
      - save_cache:
          paths:
            - ~/.pnpm/store
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker: 
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: 'pnpm test'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master