version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install PNPM
          command: 'sudo npm install -g pnpm@latest'
      - run:
          name: Install dependencies
          command: 'pnpm install'      
  test:
    docker: 
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Test
          command: 'pnpm test'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master